captainVersion: 4
services:
    $$cap_appname:
        restart: unless-stopped
        environment:
            PORT: 3000
            CORS_ORIGINS: $$cap_cors_origins
            IFRAME_ORIGINS: $$cap_iframe_origins
            FLOWISE_USERNAME: $$cap_username
            FLOWISE_PASSWORD: $$cap_password
            FLOWISE_FILE_SIZE_LIMIT: $$cap_file_size_limit
            DEBUG: $$cap_debug
            DATABASE_TYPE: postgres
            DATABASE_PORT: 5432
            DATABASE_HOST: srv-captain--$$cap_appname-db
            DATABASE_NAME: flowise
            DATABASE_USER: flowise
            DATABASE_PASSWORD: $$cap_db_password
            OVERRIDE_DATABASE: $$cap_sync_db_on_restart
            LOG_LEVEL: $$cap_log_level
            LOG_PATH: /root/.flowise/logs
            APIKEY_PATH: /root/.flowise/api_key
            SECRETKEY_PATH: /root/.flowise/secret_key
            FLOWISE_SECRETKEY_OVERWRITE: $$cap_secretkey_overwrite
            STORAGE_TYPE: $$cap_storage_type
            BLOB_STORAGE_PATH: /root/.flowise/storage
            S3_STORAGE_BUCKET_NAME: $$cap_s3_bucket_name
            S3_STORAGE_ACCESS_KEY_ID: $$cap_s3_access_key_id
            S3_STORAGE_SECRET_ACCESS_KEY: $$cap_s3_secret_access_key
            S3_STORAGE_REGION: $$cap_s3_region
            DISABLE_FLOWISE_TELEMETRY: $$cap_disable_telemetry
            MODEL_LIST_CONFIG_JSON: $$cap_model_list_config_json
            TOOL_FUNCTION_BUILTIN_DEP: $$cap_tool_function_builtin_dep
            TOOL_FUNCTION_EXTERNAL_DEP: $$cap_tool_function_external_dep
            LANGCHAIN_TRACING_V2: $$cap_langchain_tracing_v2
            LANGCHAIN_ENDPOINT: $$cap_langchain_endpoint
            LANGCHAIN_API_KEY: $$cap_langchain_api_key
            LANGCHAIN_PROJECT: $$cap_langchain_project
        volumes:
            - $$cap_appname-data:/root/.flowise
        caproverExtra:
            containerHttpPort: 3000
            dockerfileLines: |
                - 'FROM flowiseai/flowise'
                - 'RUN mkdir -p /root/.flowise /root/.flowise/logs /root/.flowise/storage /root/.flowise/api_key /root/.flowise/secret_key'
                - 'RUN chmod -R 777 /root/.flowise'
                - 'RUN chown -R 777 node:node /root/.flowise'
                - 'EXEC sleep 3 && flowise start'
        depends_on:
            - $$cap_appname-db
    $$cap_appname-db:
        image: 'postgres:$$cap_postgres_version'
        restart: unless-stopped
        environment:
            POSTGRES_DB: flowise
            POSTGRES_PASSWORD: $$cap_db_password
            POSTGRES_USER: flowise
            POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
        volumes:
            - '$$cap_appname-db-data:/var/lib/postgresql/data'
        caproverExtra:
            notExposeAsWebApp: true
caproverOneClickApp:
    variables:
        - id: $$cap_postgres_version
          label: PostgreSQL Version
          defaultValue: '15.6'
          description: The version of PostgreSQL to use.
          type: text
        - id: $$cap_db_password
          label: Database Password
          defaultValue: $$cap_gen_random_hex(20)
          description: The password for the database user.
          type: text
        - id: $$cap_cors_origins
          label: Allowed Origins for CORS
          defaultValue: '*'
          description: The allowed origins for all cross-origin HTTP calls.
          type: text
        - id: $$cap_iframe_origins
          label: Allowed Origins for Iframe Embedding
          defaultValue: '*'
          description: The allowed origins for iframe src embedding.
          type: text
        - id: $$cap_username
          label: Flowise Username
          defaultValue: admin
          description: The username to login to Flowise.
          type: text
        - id: $$cap_password
          label: Flowise Password
          defaultValue: $$cap_gen_random_hex(20)
          description: The password to login to Flowise.
          type: text
        - id: $$cap_file_size_limit
          label: Upload File Size Limit
          defaultValue: 50mb
          description: The maximum file size allowed for uploads.
          type: text
        - id: $$cap_debug
          label: Debug Mode
          defaultValue: false
          description: Print logs from components.
          type: boolean
        - id: $$cap_sync_db_on_restart
          label: Sync Database on Restart
          defaultValue: false
          description: Set to true to re-create schema on every restart.
          type: boolean
        - id: $$cap_secretkey_overwrite
          label: Encryption Key Overwrite
          defaultValue: null
          description: Encryption key to be used instead of the key stored in SECRETKEY_PATH.
          type: text
        - id: $$cap_log_level
          label: Log Level (error, info, verbose, debug)
          defaultValue: info
          description: Different levels of logs.
          type: text
        - id: $$cap_storage_type
          label: Storage Type
          defaultValue: local
          description: Type of storage for uploaded files. Default is local. (local, s3)
          type: text
        - id: $$cap_s3_bucket_name
          label: S3 Bucket Name
          defaultValue: null
          description: Bucket name to hold the uploaded files when STORAGE_TYPE is s3.
          type: text
        - id: $$cap_s3_access_key_id
          label: S3 Access Key ID
          defaultValue: null
          description: AWS Access Key.
          type: text
        - id: $$cap_s3_secret_access_key
          label: S3 Secret Access Key
          defaultValue: null
          description: AWS Secret Key.
          type: text
        - id: $$cap_s3_region
          label: S3 Region
          defaultValue: null
          description: Region for S3 bucket.
          type: text
        - id: $$cap_disable_telemetry
          label: Disable Telemetry
          defaultValue: false
          description: Turn off telemetry.
          type: boolean
        - id: $$cap_model_list_config_json
          label: Model List Config JSON
          defaultValue: null
          description: File path to load list of models from your local config file.
          type: text
        - id: $$cap_tool_function_builtin_dep
          label: Tool Function Built-in Dependencies
          defaultValue: null
          description: NodeJS built-in modules to be used for Tool Function.
          type: text
          example: fs, path
        - id: $$cap_tool_function_external_dep
          label: Tool Function External Dependencies
          defaultValue: null
          description: External modules to be used for Tool Function.
          type: text
          example: axios, lodash
        - id: $$cap_langchain_tracing_v2
          label: LangSmith Tracing
          defaultValue: false
          description: Turn LangSmith tracing ON or OFF.
          type: boolean
        - id: $$cap_langchain_endpoint
          label: LangSmith Endpoint
          defaultValue: null
          description: LangSmith endpoint.
          type: text
        - id: $$cap_langchain_api_key
          label: LangSmith API Key
          defaultValue: null
          description: LangSmith API Key.
          type: text
        - id: $$cap_langchain_project
          label: LangSmith Project
          defaultValue: null
          description: Project to trace on LangSmith.
          type: text
    instructions:
        start: |-
            Flowise is an open source low-code tool for developers to build customized LLM orchestration flow & AI agents. 
            Checkout https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md and https://docs.flowiseai.com/configuration/environment-variables to learn how to configure the environment variables.
        end: |-
            1. Access your app at https://$$cap_appname.$$cap_root_domain/
            2. Login with the following credentials:
                - Username: $$cap_username
                - Password: $$cap_password

            ## Postgres Database
            - Database Name: flowise
            - Database User: flowise
            - Database Password: $$cap_db_password
            - Database Host: srv-captain--$$cap_appname-db
            - Database Port: 5432
    displayName: Flowise AI - LLM Orchestration Tool
    isOfficial: true
    description: >-
        Flowise is an open-source low-code platform for building, deploying, and sharing customized LLM orchestration flows and AI agents, empowering developers to create AI solutions quickly and easily.
    documentation: >-
        Taken from https://docs.flowiseai.com | Official Website is https://flowiseai.com
