name: Publish One Click Apps

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21'

            - name: Install dependencies
              run: npm ci

            - name: Validate and format code
              run: npm run validate_apps && npm run formatter

            - name: Build and publish project
              run: npm run publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Deploy to GitHub Pages
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git fetch origin gh-pages
                  git checkout gh-pages
                  git rm -rf .  # Clear old content
                  git checkout master -- dist
                  mv dist/* . && rm -rf dist  # Move new build
                  touch .nojekyll # Create .nojekyll file to prevent gh-pages from building
                  git add .
                  git commit -m "Deploy to GitHub Pages"
                  git push origin gh-pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              continue-on-error: true

            - name: Error Handling
              if: failure()
              run: echo "Deployment failed. Please check logs."
